### ISSUE TITLE
Can we have a function to show both d/c/dc and highest damage as for now we can only choose one of them?

### ISSUE THREAD

**Issue by y1052895290** [dsrkafuu/skyline-overlay#15]

**Comment by dsrkafuu** [comment]
Considering that it is a horizontal overlay, displaying one line of text above and below the square is probably the limit for this feature.

However, I'm considering adding settings to freely select the specific content of the upper and lower lines of text to display, so that (no need to display the id of the player) is more convenient for a team that doesn't have the same job to access more info directly.

Direct hit pct and other information can be easily viewed through the ticker below though.
